# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 solutions.

# This is a not a c-language project but we use the same environment.
language: c
dist: xenial

# --depth flag is breaking our merge, try disabling it
# NOTE: We may be able to go back to depth=50 in production
git:
    depth: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev gfortran
    - doxygen graphviz flex bison cmake

before_install:
    - pip install --user f90nml

jobs:
  include:
    - env: JOB="Code style compliance"
      script:
        - ./.testing/trailer.py -e TEOS10 -l 120 src config_src
    - env: JOB="Doxygen"
      script:
        - cd docs && doxygen Doxyfile_nortd
        - grep -v "config_src/solo_driver/coupler_types.F90" doxygen.log | tee doxy_errors
        - test ! -s  doxy_errors
    - env: JOB="Compile and run"
      script:
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - TRAVIS_IS_PR=$( [ ${TRAVIS_PULL_REQUEST} = "false" ] || echo "true" )
        - cd .testing
        - make \
            MKMF_TEMPLATE=linux-ubuntu-xenial-gnu.mk \
            MOM_TARGET_SLUG=${TRAVIS_REPO_SLUG} \
            MOM_TARGET_LOCAL_BRANCH=${TRAVIS_BRANCH} \
            DO_REGRESSION_TESTS=${TRAVIS_IS_PR} \
            REPORT_COVERAGE=true
        - echo -en 'travis_fold:end:script.1\\r'
        - echo 'Running tests...' && echo -en 'travis_fold:start:script.2\\r'
        - make DO_REGRESSION_TESTS=${TRAVIS_IS_PR} test
        - echo -en 'travis_fold:end:script.2\\r'
