# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 solutions.

# This is a not a c-language project but we use the same environment.
language: c
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev gfortran
    - mpich libmpich-dev
    - graphviz flex bison cmake
    - python-numpy python-netcdf4
    - python3 python3-dev python3-venv python3-pip python3-sphinx python3-lxml
    - bc
    - perl
    - texlive-binaries texlive-base bibtool tex-common texlive-bibtex-extra

# Environment variables
env:
  global:
    - TIMEFORMAT: "\"Time: %lR  (user: %lU, sys: %lS)\""
    - FCFLAGS_DEBUG: "\"-g -O0 -Wextra -Wno-compare-reals -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds\""
    - FCFLAGS_REPRO: "\"-g -O2 -fbacktrace\""
    - FCFLAGS_INIT: "\"-finit-real=snan -finit-integer=2147483647 -finit-derived\""
    - FCFLAGS_COVERAGE: "\"--coverage\""
    - DO_REPRO_TESTS: true

jobs:
  include:
    - env: JOB="Code compliance"
      script:
        # Whitespace
        - ./.testing/trailer.py -e TEOS10 -l 120 src config_src
        # API Documentation
        - perl -e 'print "perl version $^V" . "\n"'
        - cd docs && mkdir _build && make nortd DOXYGEN_RELEASE=Release_1_8_13 UPDATEHTMLEQS=Y
        - grep "warning:" _build/doxygen_warn_nortd_log.txt | grep -v "as part of a" | tee doxy_errors
        - test ! -s  doxy_errors

    - env:
        - JOB="x86 verification testing"
        - DO_REGRESSION_TESTS=false
      script:
        - cd .testing
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - time make all
        - echo -en 'travis_fold:end:script.1\\r'
        - time make -k -s test
        - make test.summary

    # NOTE: Code coverage upload is here to reduce load imbalance
    # We do coverage with the regressions if part of a pull request
    # otherwise as a separate job.
    - if: type = pull_request
      env:
        - JOB="x86 Regression testing"
        - DO_REGRESSION_TESTS=true
        - REPORT_COVERAGE=true
        - MOM_TARGET_SLUG=${TRAVIS_REPO_SLUG}
        - MOM_TARGET_LOCAL_BRANCH=${TRAVIS_BRANCH}
      script:
        - cd .testing
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - time make build.regressions
        - echo -en 'travis_fold:end:script.1\\r'
        - time make -k -s test.regressions
        - make test.summary

    - if: NOT type = pull_request
      env:
        - JOB="Coverage upload"
        - REPORT_COVERAGE=true
        - DO_REGRESSION_TESTS=false
      script:
        - cd .testing
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - make build/symmetric/MOM6
        - echo -en 'travis_fold:end:script.1\\r'
        - make -k -s run.symmetric

    - arch: arm64
      env:
        - JOB="ARM64 verification testing"
        - DO_REGRESSION_TESTS=false
        - DO_REPRO_TESTS=false
      script:
        - cd .testing
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - time make all
        - echo -en 'travis_fold:end:script.1\\r'
        - time make -k -s test
        - make test.summary
